name: client
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Script
# Launch icon: flutter pub run flutter_launcher_icons
# flutter pub run build_runner build --delete-conflicting-outputs
# flutter pub run build_runner clean
# flutter pub run easy_localization:generate --source-dir 'assets/translations' --output-dir 'lib/generated' --output-file 'translations.g.dart' --format keys
# flutter build apk

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.5
  get: ^4.6.5

  # For Model
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1

  # For Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  http: ^0.13.6

  # Utils
  bot_toast: ^4.0.4
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.1
  permission_handler: ^11.0.1
  cached_network_image: ^3.2.3

  # Camera
  camera: ^0.10.5+5

  # For show video from esp32
  flutter_mjpeg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # For Builder
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0

  # For Model
  freezed: ^2.4.1

  # For Networking
  retrofit_generator: ^6.0.0+1

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
